name: Code Analysis

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install cppcheck
        run: sudo apt-get update && sudo apt-get install -y cppcheck

      - name: Run CppCheck and save output
        run: cppcheck . > cppcheck_output.txt 2>&1

      - name: Check for issues
        run: |
          if [ -s "cppcheck_output.txt" ] && grep -q "error" cppcheck_output.txt; then
            echo "Errors found. Workflow failed."
            exit 1
          else
            echo "No errors found. Proceeding with push."
          fi

      - name: Push changes
        if: success()
        run: git push origin main
